### ISSUE TITLE
Bonus: Απορίες

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/help#10]
Σε αυτήν την περιοχή γίνεται η συζήτηση και οι απορίες για όλες τις [εργασίες μπόνους](https://courses-ionio.github.io/projects/bonus/).

**Comment by epidrome** [comment]
σχετικά με την εργασία μπόνους χαρτογράφησης:

σε αυτό το στάδιο η εφαρμογή είναι διαθέσιμη μόνο από την ιστοσελίδα του συστήματος
https://peersonmap.herokuapp.com/#download

όπου πατώντας στο εικονίδιο της εφαρμογής (πορτοκαλί εικονίδιο - PoM) μπορείς να κατεβάσεις το PoM.apk

Προσοχή: αν δεν ανοίξεις το παραπάνω link από τον browser στο κινητό σου,
αλλά από κάποιο άλλο pc, θα πρέπει να μεταφέρεις το PoM.apk στο κινητό σου για να ξεκινήσεις την εγκατάσταση.

**Comment by ConstantineXipol** [comment]
Καλησπέρα/Καλημέρα ανάλογα ποτε σας βρίσκω. Για την εργασία μπόνους χαρτογράφησης: βρηκα ενα μεγαλουτσικο bug, να το γραψω εδω η να στειλω email εκει που λεει στο about?

Επισης δεν καταλαβα τι ακριβως εννοειτε με το "εντοπίσουν μονοπάτια και να σχεδιάσουν διορθώσεις τους", δηλαδη αν καποιος παει λιγο παραπερα στο πεζοδρομιο πχ, να το αλλαζουμε?? 

Και ενα τελευταιο, οι βαθμολογησεις μονοπατιων μετρουν στις "διορθωσεις"? Ευχαριστω!!

**Comment by antpapapolyzos** [comment]
Καλημέρα,

για τη σχεδίαση διορθώσεων μονοπατιών που έχουν ήδη καταγραφεί θα πρέπει να μεταβείς από το μενού στην οθόνη "Αξιολόγηση-Σχεδίαση". Στο χάρτη αυτής της οθόνης εμφανίζονται τα διαθέσιμα μονοπάτια που έχουν καταγραφεί και βρίσκονται σε μια ακτίνα γύρω από την τρέχουσα θέση σου.
Θα πρέπει να επιλέξεις ένα από αυτά πατώντας πάνω του (στο σημείο αυτό εμφανίζεται παράθυρο με οδηγίες για την αξιολόγηση και τη σχεδίαση) και στη συνέχεια με ένα μακρύ πάτημα (long tap) να ορίσεις το σημείο έναρξης και επίσης με ένα μακρύ πάτημα να ορίσεις το σημείο τερματισμού του τμήματος του μονοπατιού που προτείνεις ως διόρθωση του επιλεγμένου. Στη συνέχεια πατώντας το πλήκτρο αποστολή σχεδίασης, καταχωρείς την πρότασή σου. Ουσιαστικά είναι μια διαδικασία snap-to-road για το μονοπάτι που καταγράφηκε αρχικά. 

Οι βαθμολογήσεις μονοπατιών δε μετρούν ως διορθώσεις, αλλά σου δίνουν επιπλέον πόντους.

Για το bug που εντόπισες καλό θα ήταν να το στείλεις στο email που αναφέρεται στο about.

**Comment by ConstantineXipol** [comment]
Καλησπέρα, σχετικά με τα όρια bonus στις εργασίες, μπορώ για παράδειγμα να παρω 1 βαθμό απο github pages, και 1 βαθμό από την εφαρμογή PeersOnMap? Δλδ Σύνολο 2 βαθμοί που είναι και το όριο (κανονικά απο το PeersOnMap πρέπει να πάρω 1,5 βαθμο)

github page: https://constantinexipol.github.io/sw/projects/2014116/

**Comment by epidrome** [comment]
Οπως λέει στην εκφώνηση: "Υπάρχουν οι παρακάτω διαθέσιμες εργασίες για μπόνους βαθμό, μπορείτε να διαλέξετε μόνο μια για κάθε μάθημα με μέγιστο 2 βαθμούς μπόνους"
https://courses-ionio.github.io/projects/bonus/

Αρα, μπορούμε να δώσουμε το μέγιστο δυνατό μπόνους από *μία μόνο* εργασία για κάθε μάθημα, π.χ., 1.5 βαθμό για το PoM, στην περίπτωση που είσαι στους 3 πρώτους.

**Comment by ConstantineXipol** [comment]
Έγινε ευχαριστώ, κράτησα και το github pages απλώς λέω στην αναφορά οτι δεν είναι για bonus.
