### ISSUE TITLE
pacman local

### ISSUE THREAD

**Issue by TomasVasileiadhs** [courses-ionio/help#12]
Καλησπέρα. Έχω κάνει clone το repository που αφορά το παραδοτέο με το pacman. Προσπαθώ να ανοίξω το index.html στον browser, το οποίο θα περιέχει το βασικό κορμό του παιχνιδιού και το μόνο που βλέπω είναι μια μαύρη οθόνη. Θα έπρεπε να γίνεται έτσι ή θα έπρεπε να βλέπω την αρχική έκδοση του παιχνιδιού;

Ευχαριστώ για τον χρόνο σας.

**Comment by merkourisa** [comment]
Καλησπέρα,
Θα έπρεπε να βλέπεις το παιχνίδι: https://ioniodi.github.io/pacman/

**Comment by TomasVasileiadhs** [comment]
Το γνωρίζω. Αλλά παρόλαυτά βλέπω μια μαύρη οθόνη. Χρησιμοποιώ Ubuntu 16.04 με default browser.

**Comment by merkourisa** [comment]
F12 για να δεις τι μπορεί να φταίει; chromium ή mozilla?

**Comment by TomasVasileiadhs** [comment]
Mozila

**Comment by TomasVasileiadhs** [comment]
Χρησιμοποίησα το F12 και παίρνω αυτό το μήνυμα από το console: ReferenceError: Phaser is not defined[Learn More]

**Comment by merkourisa** [comment]
Μάλλον πρέπει να ψάξεις λίγο στο διαδίκτυο τι μπορεί να φταίει ή να δοκιμάσεις κάποιο άλλο browser

**Comment by TomasVasileiadhs** [comment]
Μόλις δοκίμασα όλους τους browser (Opera, Chromium) και παίρνω το ίδιο αποτέλεσμα. Στην συνέχεια ακολούθησα την εγκατάσταση για το npm και nodejs, και στην συνέχεια εγκατέστησα το phaser-ce. Ακόμη υπάρχει το ίδιο πρόβλημα.

![screenshot from 2017-07-26 15-40-03](https://user-images.githubusercontent.com/30369655/28621170-be36034e-7218-11e7-8e4c-8944ec7971d1.png)

**Comment by merkourisa** [comment]
Σε mozilla/mint που το δοκίμασα κανονικά

**Comment by TomasVasileiadhs** [comment]
Το link που μου δώσατε όταν το άνοιξα το παιχνίδι λειτουργούσε κανονικά. Παρ'όλ'αυτά υπάρχει πρόβλημα με το index.html

**Comment by TomasVasileiadhs** [comment]
Βρήκα το λάθος. Στο depository του παιχνιδιού που μας δίνεται, στο αρχείο index.html υπήρχε λάθος στο path του script. Άλλαξα το path για το script και είναι κάπως έτσι πλέον. <script src="/home/tom/phaser-ce-2.8.3/build/phaser.min.js"></script>

![screenshot from 2017-07-26 19-14-12](https://user-images.githubusercontent.com/30369655/28631698-cbe1c7bc-7236-11e7-91bf-d5f56b18af26.png)

**Comment by merkourisa** [comment]
Αλλά έτσι θα τρέχει μόνο στο δικό σου το pc

**Comment by TomasVasileiadhs** [comment]
Τις έχω διαβάσει και προσπάθησα να κάνω ότι έλεγε η εκφώνηση.
