### ISSUE TITLE
Αποστολή παραδοτέου

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/help#17]
Ερωτήσεις, απαντήσεις, βοήθεια και συμβουλές για την αποστολή παραδοτέου με το σύστημα του Github

**Comment by Theblackdemoniv** [comment]
Επειδη μαλλον ξερω να κανω αναζητηση στο ιντερνετ , λεει οτι με το που διαγραψεις ενα acc διαγραφονται και ολα οσα εχεις δημιουργησει στο acc αυτο . Το θεμα ειναι οτι στο acc που διαγραψα και μετα εφτιαξα ενα αλλο, δεν διαγραφηκαν τα αρχεια που ειχα φτιαξει

**Comment by Theblackdemoniv** [comment]
(Θυμηθείτε ότι όλα τα αποθετήρια, τα πιρούνια των ιδιωτικών αποθετηρίων, τα wikis, τα ζητήματα, τα αιτήματα έλξης και τις σελίδες που ανήκουν στο λογαριασμό σας θα διαγραφούν, η χρέωση θα λήξει και το όνομα χρήστη σας θα είναι διαθέσιμο σε οποιονδήποτε για χρήση στο GitHub.)
Οταν διαγραφεις ενα acc γινονται τα απο πανω σε εμενα οταν το εκανα αυτο δεν διαγραφηκαν. Οποτε δεν μπορω να αλλαξω το REWORK2016080 αφου μου λεει οτι υπαρχει ηδη φακελος με ονομα 2016080.

**Comment by mkamgit** [comment]
Δεν βρίσκω λόγο ενώ έχεις φτιάξει σωστά το φάκελό σου, να φτιάχνεις καινούριο acc  με λάθος το φάκελό σου και έπειτα να διαγράφεις το αρχικό acc σου (κάτι το οπόιο δεν μου είχες αναφέρει). Παρόλα αυτά διέγραψα τον προηγούμενο φάκελο και μπορείς να προχωρήσεις.
