### ISSUE TITLE
Κινητά και Κοινωνικά Μέσα: Απορίες

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/help#24]
Σε αυτήν την περιοχή μπορείτε να στέλνετε απορίες σχετικά με το μάθημα του τίτλου.

Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο, π.χ., για την εργασία pacman https://github.com/ioniodi/corfu-map/issues και αντίστοιχα για την εργασία που έχετε

Αν το ερώτημα σχετίζεται με την αποστολή παραδοτέου, υπάρχει ήδη αντίστοιχο θέμα

**Comment by stilos25** [comment]
Καλησπέρα, ήθελα να ρωτήσω στην περίπτωση που δεν δουλέψουν όλα τα υποερωτήματα  του 2ου παραδοτέου, αν θα μπορούσαμε να προσπαθήσουμε το 3ο παραδοτέου για να συμπληρώσουμε  τον βαθμό μας.
