### ISSUE TITLE
Εργασία Μπόνους(PI Book)

### ISSUE THREAD

**Issue by MyrtoP** [courses-ionio/help#27]
Στην εκφωνηση του μπόνους το λινκ για το βιβλιο δεν λειτουργεί, οπότε πως μπορούμε να έχουμε πρόσβαση στο λινκ αυτό για να το δημοσιεύσουμε;
Στις 28 φεβρουαρίου έστειλα ερώτημα αλλά δεν μπόρεσε να λυθεί το πρόβλημα εξακολουθώ να μπορώ να πάρω το μπόνους;

**Comment by bgarnb** [comment]
@MyrtoP στις οδηγίες γράφει ότι πρέπει πρώτα να δημιουργήσετε σε ξεχωριστό κλαδί το αντίστοιχο αρχείο αναφοράς που θα περιλαμβάνει αρχικά ένα λινκ στον λογαριασμό σας σε ένα κοινωνικό μέσο και στη συνέχεια να πάρετε την έγκριση του καθηγητή

**Comment by epidrome** [comment]
@MyrtoP 
1.ποιο ακριβώς λινκ δεν λειτουργεί? πάντα μπορείς να στείλεις ένα πουλ ρικουεστ αν βρεις κάποιο λάθος.
https://courses-ionio.github.io/projects/bonus/
2. που έστειλες ερώτημα?
3. όπως λένε οι οδηγίες μπορείς να στείλεις περισσότερες απορίες στο αποθετήριο της εργασίας οπότε το κλείνω εδώ και ας το δούμε στην αντίστοιχη περιοχή

**Comment by MyrtoP** [comment]
Ευχαριστώ που απαντήσατε στο Μυνημα αλλά τελικά δεν θα κάνω αυτό το bonus
διότι πρόλαβα και έκανα την χαρτογράφηση

Στις 10 Μαρ 2018 12:58 μ.μ., ο χρήστης "Konstantinos Chorianopoulos" <
notifications@github.com> έγραψε:
