### ISSUE TITLE
SW

### ISSUE THREAD

**Issue by mskafi28** [courses-ionio/help#32]
Αν η εξεταστική του Φεβρουαρίου είναι διπλή, μπορούν οι επί πτυχίω φοιτητές να παραδώσουν εργασία για το μάθημα της Τεχνολογίας Λογισμικού παρόλο που είναι μάθημα εαρινού εξαμήνου;

**Comment by epidrome** [comment]
γίνεται αλλά υπάρχουν καποιοι περιορισμοί, π.χ. μικρότερος βαθμός, χωρίς βοήθεια
https://courses-ionio.github.io/help/faq/

καθώς και εντοπισμός των εργασιών του εαρινού εξαμήνου στο ιστορικό
https://courses-ionio.github.io/projects/
