### ISSUE TITLE
Τεχνολογία Λογισμικού (SW): Ανακοινώσεις

### ISSUE THREAD

**Issue by diogenisAl** [courses-ionio/help#34]
Κάντε εγγραφή (**subscribe**) σε αυτό το θέμα (github issue) ώστε να λαμβάνετε άμεσα ειδοποιήσεις (**notifications**) που σχετίζονται με το μάθημα, π.χ. για τις ώρες των συναντήσεων σε περίπτωση ακύρωσης/αναπλήρωσης κ.ά.

[Οδηγίες για την χρήση των issues-notifications](https://guides.github.com/features/issues/)

**Comment by geocfu** [comment]
Καλησπέρα, θα πραγματοποιηθεί το σημερινό μάθημα 14/02;

**Comment by epidrome** [comment]
το μάθημα θα αναπληρωθεί αύριο Παρασκευή 15 Φεβ 7μμ Αρεταίος Αιθ.3

λυπάμαι που δεν πρόλαβα να βγάλω ανακοίνωση έγκαιρα :-/

**Comment by apanaretos** [comment]
Αναβολή εργαστηρίου μαθήματος "Τεχνολογία Λογισμικού" - 25.02.2019
Το εργαστήριο του μαθήματος "Τεχνολογία Λογισμικού" - Δευτέρα 25.02.2019 και ώρα 09.00 - 11.00 αναβάλλεται λόγω ασθένειας του διδάσκοντος.

**Comment by epidrome** [comment]
Το μάθημα της Πέμπτης 28 Φεβ. δεν θα γίνει και θα αναπληρωθεί με επόμενη ανακοίνωση.

**Comment by epidrome** [comment]
Σήμερα Παρασκευή 15 Μαρτίου θα γίνει αναπλήρωση στις 7μμ στον Αρεταίο Αιθ.3

**Comment by epidrome** [comment]
Για τα επόμενα μαθήματα μπορείτε να στέλνετε αίτημα για συνάντηση είτε στο #38 είτε στο https://telegram.me/epidrome ώστε να κάνετε παρουσίαση της προόδου στην εργασία ανάπτυξης

**Comment by epidrome** [comment]
Στο επόμενο μάθημα Πέμπτη 18 Απριλίου 7μμ μπορείτε να παρουσιάσετε το τελικό παραδοτέο του μπόνους ή/και της προόδου στην εργασία ανάπτυξης για σχολιασμό ή/και πιθανές βελτιώσεις πριν γίνει η τελική βαθμολόγηση τους

Επίσης, θα γίνει αναπλήρωση μαθήματος την Παρασκευή 19 Απριλίου στις 9πμ

Φυσικά, μπορείτε να συνεχίσετε να στέλνετε και αιτήματα για επιπλέον συναντήσεις στο γραφείο-εργαστήριο για απορίες σχετικές με το λογισμικό που αναπτύσετε

**Comment by geocfu** [comment]
@epidrome 
Θα πραγματοποιηθεί το μάθημα στις 9/5;

**Comment by epidrome** [comment]
Ισχύουν οι κανονικές ώρες, καθώς και η δυνατότητα για επιπλέον συναντήσεις στο #38

**Comment by riggas-ionio** [comment]
**Έναρξη εργαστηρίου μαθήματος "Τεχνολογία Λογισμικού" στις 20.02.2020**
Το εργαστήριο του μαθήματος "Τεχνολογία Λογισμικού" την Πέμπτη 13.02.2020 δεν θα πραγματοποιηθεί λόγω ίωσης, η έναρξη των εργαστηρίων θα γίνει την επόμενη Πέμπτη 20 Φεβρουαρίου.
