### ISSUE TITLE
Τεχνολογία Λογισμικού (SW): Απορίες

### ISSUE THREAD

**Issue by diogenisAl** [courses-ionio/help#35]
Σε αυτήν την περιοχή μπορείτε να στέλνετε **γενικές απορίες** σχετικά με το **μάθημα**.

Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο της εργασίας.

**Comment by ThomasVasileiadis** [comment]
Καλησπέρα, έχω διαλέξει την εργασία [Συνεργατική κατασκευή οδηγού σπουδών](https://github.com/ioniodi/study-guide/)    και στέλνω αναφορικά με την εκφώνηση της άσκησης. 


Όταν λέτε " _Ο σκοπός της εργασίας είναι να γίνει συνεργατική επεξεργασία του αρχικού αρχείου και οργάνωση του σε επιμέρους αρχεία_ "  ποιο εννοείτε ότι είναι το αρχικό αρχείο;

**Comment by geocfu** [comment]
Ερώτηση για το Bonus (CV).

Καλησπέρα,
θα ήθελα να ρωτήσω αν είναι απαραίτητο να κάνουμε ένα gif που να δείχνει ότι το αποτέλεσμα είναι αποκλειστικά από το pandoc, αφού, έχοντας συμπεριλάβει το CI (Continuous Integration), τα commits γίνονται από το ίδιο το CI bot.

Ευχαριστώ εκ των προτέρων

**Comment by epidrome** [comment]
όπως λένε οι οδηγίες
για να γίνει η βαθμολόγηση
θα πρέπει να υπάρχει αναφορά με λινκ-εικόνες
που να πιστοποιούν την ζωντανή εκτέλεση

**Comment by geocfu** [comment]
Συνεπώς θα συμπεριλάβω στην τελική αναφορά μου στο τέλος ένα gif. Ευχαριστώ.
