### ISSUE TITLE
Εξυπνα περιβάλλοντα και εφαρμογές: Ανακοινώσεις

### ISSUE THREAD

**Issue by mkamgit** [courses-ionio/help#36]
Κάντε εγγραφή (**subscribe**) σε αυτό το θέμα (github issue) ώστε να λαμβάνετε άμεσα ειδοποιήσεις (**notifications**) που σχετίζονται με το μάθημα, π.χ. για τις ώρες των συναντήσεων σε περίπτωση ακύρωσης/αναπλήρωσης κ.ά.

**Comment by epidrome** [comment]
Το μάθημα γίνεται με ανάθεση εργασίας όπως περιγράφεται:
https://github.com/courses-ionio/projects/blob/master/soc/index.md

Για την ανάθεση εργασίας καθώς και για την επίβλεψη της προόδου μπορείτε να ζητήσετε συνάντηση στο παρακάτω θέμα:
https://github.com/courses-ionio/help/issues/38

**Οι δια ζώσης συναντήσεις του μαθήματος γίνονται μόνο μετά από ραντεβού στο παραπάνω θέμα στις ώρες του μαθήματος στο εργαστήριο Πληροφορικής στις Ανθρωπιστικές Επιστήμες στον 2ο όροφο στο κτίριο της γραμματείας**
