### ISSUE TITLE
Συνεργατικές Εφαρμογές (Msc): Ανακοινώσεις

### ISSUE THREAD

**Issue by c15pati** [courses-ionio/help#40]
Κάντε εγγραφή (**subscribe**) σε αυτό το θέμα (github issue) ώστε να λαμβάνετε άμεσα ειδοποιήσεις (**notifications**) που σχετίζονται με το μάθημα, π.χ. για τις ώρες των συναντήσεων σε περίπτωση ακύρωσης/αναπλήρωσης κ.ά.

[Οδηγίες για την χρήση των issues-notifications](https://guides.github.com/features/issues/)

**Comment by epidrome** [comment]
Σας θυμίζω την προθεσμία για το 1ο και 2ο παραδοτέο αύτην την Κυριακή 14 Απριλίου

Στο e-class του μαθήματος θα βρείτε δωρεάν λινκ-κουπόνι για την ηλεκτρονική έκδοση του βιβλίου του μαθήματος, το οποίο μαζί με την ιστοσελίδα του βιβλίου είναι χρήσιμα για το 2ο παραδοτέο

Οπως λένε οι οδηγίες του μαθήματος, δεν μπορούμε να έχουμε παράταση για κανένα παραδοτέο, αλλά μπορούμε να βελτιώσουμε όλα τα παραδοτέα αργότερα

Το επόμενο μάθημα θα γίνει δια ζώσης στον Γαληνό σύμφωνα με το πρόγραμμα

**Comment by midipetit** [comment]
Κύριε Χωριανόπουλε καλησπέρα,

Εάν ειναι εύκολο να μας διευκρινίσετε τι ακριβώς πρεπει να κάνουμε σε οτι
αφορά το βιβλίο του μαθήματος, Γιατι δεν είχαμε καταλάβει οτι ειναι και
αυτο στην προθεσμία της 1ης εβδομάδας!

**Comment by bgarnb** [comment]
Το μάθημα θα γίνει δια ζώσης την Τρίτη 7/5 στις 18.00 στον Γαληνό.
Ευχαριστώ

**Comment by midipetit** [comment]
@epidrom Σχετικά με το μάθημα που έχουμε τις  21 Μαΐου, θα γίνει κάποια αλλαγή στη μερα ;

**Comment by epidrome** [comment]
θα το συζητήσουμε στο μάθημα της Τρίτης 14.5 και θα βγει ανακοίνωση

**Comment by epidrome** [comment]
Το επόμενο μάθημα θα γίνει δια ζώσης στον Γαληνό σύμφωνα με το πρόγραμμα

**Comment by midipetit** [comment]
@epidrome Σχετικά με το μάθημα που δεν θα γίνει αυριο, τελικά μπορείτε την Τετάρτη 3-6;;

**Comment by epidrome** [comment]
Την Τετάρτη 22 Μαϊου στις 3μμ θα γίνει το μάθημα αυτής της εβδομάδας στον Γαληνό

**Comment by c18gour** [comment]
Καλησπέρα!
Για το μάθημα εντάξει από εμένα.

**Comment by c18stat** [comment]
@epidrome Αυριο 28/5 έχουμε 3ωρο ή 6ωρο; Δια ζώσης ή εξ αποστασεως;

**Comment by epidrome** [comment]
το μάθημα θα γίνει εξ αποστάσεως σύμφωνα με το πρόγραμμα σήμερα 3-9μμ

σας έστειλα προσωπικό μυνημα από το σύστημα όπου σας ζητάω τα gmail, skype

**Comment by bgarnb** [comment]
Η τελική εξέταση θα γίνει αύριο Τρίτη 11/5 στις 6.00 μ.μ. 
Ευχαριστώ
