### ISSUE TITLE
Κινητά και κοινωνικά μέσα : Εργασίες

### ISSUE THREAD

**Issue by Pangntat** [courses-ionio/help#42]
Καλησπέρα , πότε θα αναρτηθούν οι διαθέσιμες εργασίες για το μάθημα ;

Στις εργασίες δεν βλέπω τον κωδικό CSCW

Ευχαρισώ πολύ

**Comment by epidrome** [comment]
@Pangntat 
το μάθημα φέτος δεν είναι στο πρόγραμμα
