### ISSUE TITLE
Πολυμέσα (MM): Απορίες 

### ISSUE THREAD

**Issue by c15pati** [courses-ionio/help#49]
Σε αυτήν την περιοχή μπορείτε να στέλνετε **γενικές απορίες** σχετικά με το **μάθημα**.

Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο της εργασίας.

**Comment by AlexandrosP38** [comment]
Καλησπέρα, 
Για την εξεταστική του Σεπτεμβρίου ήθελα να κάνω την εξής ερώτηση: έχω κάνει κανονικά το χειμερινό εξάμηνο όλες τις απαιτούμενες εργασίες αλλά δεν κατέστη δυνατό λόγω δουλείας να παρευρίσκομαι στις εξετασεις. Τι θα πρέπει να κάνω για τον Σεπτέμβρη? Ευχαριστώ εκ των προτέρων - Πολίτης Αλέξανδρος

**Comment by epidrome** [comment]
@AlexandrosP38 
https://github.com/courses-ionio/mm/issues/609
