### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by AlexKontop** [courses-ionio/help#50]
Προσπαθώ να κάνω την ενδιάμεση αναφορά και κάθε φορά που ανεβάζω μια εικόνα στο images μου έρχεται το εξής εμαιλ: The page build failed for the `gh-pages` branch with the following error:

A file was included in `_biography/alan-kay.md/#excerpt` that is a symlink or does not exist in your `_includes` directory

**Comment by AlexPapas1** [comment]
Το ίδιο και 'δω.

**Comment by mkamgit** [comment]
Παρακαλώ μην φτιάχνετε δικά σας issues στο αποθετήριο του μαθήματος. Ακολουθήστε τις οδηγίες.
