### ISSUE TITLE
Κινητά και Κοινωνικά Μέσα: Απορίες

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/help#6]
Σε αυτήν την περιοχή μπορείτε να στέλνετε απορίες σχετικά με το μάθημα Κινητά και Κοινωνικά Μέσα

**Comment by johnalkmeg** [comment]
Η υπάρχουσα σελίδα του τμήματος έχει δημιουργηθεί από φοιτητές;

**Comment by epidrome** [comment]
στείλτε την απορία στο αντίστοιχο θέμα
