### ISSUE TITLE
Pacman: Απορίες

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/help#7]

**Comment by maroumal** [comment]
Καλησπέρα ! Θα ήθελα να ρωτήσω αν στο παραδοτέο 2  πρέπει να κάνω όλα όσα λέει ή αν θα διαλέξω ένα από αυτά. Επίσης έχω αλλάξει τον χαρακτήρα και δούλεψε, αλλά έχω  θέμα με την τοποθέτηση επιπλέον αντικειμένων την οποία υλοποίησα αλλά δεν τρέχει. Τι μπορώ να κάνω; Ευχαριστώ.

**Comment by epidrome** [comment]
Ενα πλήρες παραδοτέο περιλαμβάνει όλα τα επιιμέρους ζητούμενα, ειδικα το ζητούμενο της δημιουργίας νέου χάρτη για το πακμαν αναλυθήκε με λεπτομέρεια στο προηγούμενο μάθημα και είναι σχετικά εύκολο. Αν χάσατε το μάθημα μπορείτε να ρωτήσετε κάποιον συμφοιτητή σας.

**Comment by balospa** [comment]
Στις οδηγίες για τη δημιουργία του pacman (https://courses-ionio.github.io/projects/pacman/) δεν καταλαβαίνω τη φράση με την εικόνα "Τέλος φορτώστε την εικόνα από το Github pages". 
Ποια εικόνα;
Τι είναι αυτό το screenshot με τον κώδικα ;
Μπορείτε να δώσετε περισσότερες λεπτομέρειες;

**Comment by merkourisa** [comment]
Οι εικόνες είναι στοιχεία του παιχνιδιού όπως ο pacman.png, dot.png κτλ. Αυτές βρίσκονται στο φάκελο assets. Για να μπορέσεις να τις χρησιμοποιήσεις στο παιχνίδι πρέπει να τις διαβάσεις όπως φαίνεται στο screenshot με τον κώδικα του παιχνιδιού. Στο load.baseUL πρέπει να βάλεις τη δική σου github διεύθυνση.

**Comment by arachnavonfenrir** [comment]
'Εχω ένα πρόβλημα , ο κώδικας φορτώνει αρχεία που δεν υπάρχουν. Είναι κανονικό αυτό;

**Comment by arachnavonfenrir** [comment]
Εδω που τα λεμε, εστιλα το " παραδοτεο" για να με προσεξοθν. Ξερω οτι εχω προβλημα, αλλα κανεις δεν απανταει....

**Comment by merkourisa** [comment]
Επειδή οι φοιτητές παραδίδουν τις εργασίες δεν ήταν δυνατόν να σου απαντήσω νωρίτερα. Το παιχνίδι σου τώρα φορτώνει αλλά χωρίς την πίστα. Προσπάθησε να το διορθώσεις
![default](https://cloud.githubusercontent.com/assets/10854690/23871440/11eed998-0833-11e7-8c8c-fd5597df872d.png)

**Comment by arachnavonfenrir** [comment]
Καταλαβαινω τι γινεται, αλλα δεν υπαρχι αιτια που να προκαλουσε τετοιο αποτελεσμα, Ολα τα αρχεια ειναι μεσα στο φακελο και οι δεικτες ειναι σωστοι, τοπικα τρεχει κανονικα, ενω το Tiled ανοιγει το αρχειο ορθα. Αμα το κατεβασετε θα φανει οπως πρεπει, για αυτον τον λογο  ρωταω, μηπως ειναι προβλημα του github?

**Comment by merkourisa** [comment]
Σίγουρα δεν είναι πρόβλημα του github. Αν δεις τα παιχνίδια από άλλους φοιτητές τρέχουν κανονικά. Στο δικό σου υπάρχει πρόβλημα:
![default](https://cloud.githubusercontent.com/assets/10854690/23871776/75634bb6-0834-11e7-8b91-8f61dab49d56.png)
