### ISSUE TITLE
ΑΠΟΡΙΑ

### ISSUE THREAD

**Issue by balospa** [courses-ionio/help#9]
Στις οδηγίες για τη δημιουργία του pacman (https://courses-ionio.github.io/projects/pacman/) δεν καταλαβαίνω τη φράση με την εικόνα "Τέλος φορτώστε την εικόνα από το Github pages".
Ποια εικόνα;
Τι είναι αυτό το screenshot με τον κώδικα ;
Μπορείτε να δώσετε περισσότερες λεπτομέρειες;

**Comment by merkourisa** [comment]
Απαντήθηκε στο pacman απορίες
